apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres-pod
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-config-volume
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
      volumes:
        - name: postgres-config-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
