apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "//C/Users/Victor Vidal/Documents/projects/personal/fiap/soat-fase-2/TECH-CHALLENGE/postgres-data/"
