# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres-pod
spec:
  containers:
    - name: postgres-pod
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      volumeMounts:
        - name: postgres-config-volume
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-config-volume
      persistentVolumeClaim:
        claimName: postgres-pvc
