# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres-pod
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
