# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: food-postgres-opaque-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
