name: Deploy Infra to AWS (EKS)

on:
  push:
    branches:
      - main  # Deploy infra only when merging to main
  workflow_dispatch:  # Allow manual deployment trigger

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform (Provision Infra)
        run: terraform apply -auto-approve
