name: Deploy API Gateway & Lambda

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build do Lambda
        run: sam build

      - name: Deploy do Lambda
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
